set nocompatible        " Use Vim defaults (much better!)
set backspace=2         " allow backspacing over everything in insert mode
set ai                  " auto indenting
set history=100         " keep 100 lines of history
set ruler               " show the cursor position
syntax on               " syntax highlighting
set hlsearch            " highlight the last searched term
filetype plugin on      " use the file type plugins
set viminfo='20,\"50    " read/write a .viminfo file, don't store more
                        " than 50 lines of registers
set incsearch           " Enable incremental search

set wildmenu
set wildmode=list:longest


" When editing a file, always jump to the last cursor position
autocmd BufReadPost *
\ if ! exists("g:leave_my_cursor_position_alone") |
\ if line("'\"") > 0 && line ("'\"") <= line("$") |
\ exe "normal g'\"" |
\ endif |
\ endif

" The following works on vim 7.3 and higher
if exists('+colorcolumn')
  " this trick was picked up from: http://bit.ly/1gkOYQU
  let &colorcolumn=join(range(80,300),",")
  highlight ColorColumn ctermbg=235 guibg=#2c2d27
endif

set tabstop=8 shiftwidth=2 expandtab

fun! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun
autocmd FileType c,cpp,java,php,ruby,python,sh,bashrc,vimrc autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()
