set nocompatible        " Use Vim defaults (much better!)
set ai                  " auto indenting
set history=100         " keep 100 lines of history
set ruler               " show the cursor position
syntax on               " syntax highlighting
set hlsearch            " highlight the last searched term
filetype plugin on      " use the file type plugins
set viminfo='20,\"50    " read/write a .viminfo file, don't store more
                        " than 50 lines of registers

" When editing a file, always jump to the last cursor position
autocmd BufReadPost *
\ if ! exists("g:leave_my_cursor_position_alone") |
\ if line("'\"") > 0 && line ("'\"") <= line("$") |
\ exe "normal g'\"" |
\ endif |
\ endif

if exists('+colorcolumn')
  set colorcolumn=80
  highlight ColorColumn ctermbg=246
endif

set tabstop=8 shiftwidth=2 expandtab

