#
# Source this file from ~/.bashrc
#

# Pick up shared settings for zsh and bash
this_dir="${BASH_SOURCE%/*}"
shared_rc="$this_dir/../share/x-rc.sh"
if [ -f "$shared_rc" ]
then
    source "$shared_rc"
else
    >&2 echo "Missing file: $shared_rc"
fi
unset shared_rc this_dir


# Make history shared and in sync across all sessions
shopt -s histappend
if [ "$PROMPT_COMMAND" == "" ]; then
    PROMPT_COMMAND="history -a; history -n"
elif [[ ! "$PROMPT_COMMAND" =~ "history -a; history -n" ]]; then
    PROMPT_COMMAND="$PROMPT_COMMAND; history -a; history -n"
fi
