#
# Source this file from ~/.bashrc
#

# Pick up shared settings for zsh and bash
this_dir="${BASH_SOURCE%/*}"
shared_rc="$this_dir/../share/x-rc.sh"
if [ -f "$shared_rc" ]
then
    source "$shared_rc"
else
    >&2 echo "Missing file: $shared_rc"
fi
unset shared_rc this_dir

# Make history shared and in sync across all sessions
shopt -s histappend
if [ "$PROMPT_COMMAND" == "" ]; then
    PROMPT_COMMAND="history -a; history -n"
elif [[ ! "$PROMPT_COMMAND" =~ "history -a; history -n" ]]; then
    PROMPT_COMMAND="$PROMPT_COMMAND; history -a; history -n"
fi

# More history settings
export HISTCONTROL=ignoredups       # Skip dupes when searching history
# export HISTTIMEFORMAT="[%F %T] "  # Optional 

# Allow Ctrl-S to be used for forward history search as in:
# http://www.gnu.org/software/bash/manual/html_node/Searching.html
# However Ctrl-S collides with XON/XOFF flow control. The following command
# disables XON/XOFF
if [ -t 0 ]; then   # only run if stdin is a terminal
    stty -ixon
fi

# Set up SCM prompt.
# The following works only if the function "_dotfiles_scm_info" is defined and
# outputs the desired scm info. You can find such a function. E.g., see
# https://github.com/wavesoftware/scmprompt or 
# https://github.com/ryanmce/dotfiles/blob/master/scm-prompt.sh
if type -t _dotfiles_scm_info > /dev/null; then
    preprompt() {
	branch="$(_dotfiles_scm_info)"
	colored_branch=$'\e[38;5;162m'$'\e[48;5;234m'"$branch"$'\e[m'
	if [ -n "$branch" ]
	then
	    printf "%$((`tput cols`+25))s`tput cr`" "$colored_branch"
	fi
    }
    PROMPT_COMMAND=preprompt
fi

export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\] '

case `uname` in
Darwin)
    # Add brew completion for bash. For this to work, first install:
    # $ brew install bash-completion
    if which brew > /dev/null ; then
        if [ -r $(brew --prefix)/etc/profile.d/bash_completion.sh ]; then
            . $(brew --prefix)/etc/profile.d/bash_completion.sh
        fi
    fi
    ;;
Linux)
    ;;
esac

