#
# Source this file from ~/.zshrc
#

# Pick up shared settings for zsh and bash
this_dir="$(dirname "$0")"
shared_rc="$this_dir/../share/x-rc.sh"
if [ -f "$shared_rc" ]
then
    source "$shared_rc"
else
    >&2 echo "Missing file: $shared_rc"
fi
unset shared_rc this_dir

case `uname` in
Darwin)
    if type brew &>/dev/null
    then
        FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

        autoload -Uz compinit
        compinit
    fi
    ;;
Linux)
    ;;
esac

# History settings
setopt INC_APPEND_HISTORY  # Add commands to history immediately, not only upon shell exit
setopt EXTENDED_HISTORY    # Record timestamp of each command
setopt HIST_FIND_NO_DUPS   # Skip dupes when searching history
setopt SHARE_HISTORY       # Share history between terminal sessions

bindkey '^R' history-incremental-search-backward